version: "3.8"
services:
  job-service:
    image: microservice-platform-job-service:1.0.0-dev
    container_name: microservice-platform-job-service-dev
    build:
      context: ../../
      dockerfile: docker/nest/dev.dockerfile
    working_dir: /home/node/workspace
    command: npx nx serve job-service
    restart: unless-stopped
    tty: true
    volumes:
      - ../../:/home/node/workspace
      - /home/node/workspace/apps/
      - .:/home/node/workspace/apps/job-service
      - /home/node/workspace/node_modules
    networks:
      - microservice-platform-server_microservice-platform-network
    env_file:
      - ../../.env.global.dev
      - .env.dev

networks:
  microservice-platform-server_microservice-platform-network:
    external: true