version: "3.8"
services:
  user-service:
    image: microservice-platform-user-service:1.0.0
    container_name: microservice-platform-user-service
    build:
      context: ./
      dockerfile: ../../docker/nest/Dockerfile
    restart: unless-stopped
    ports:
      - 3333:8000
