version: "3.8"
services:
  game-user-gateway:
    image: microservice-platform-game-user-gateway:1.0.0
    container_name: microservice-platform-game-user-gateway
    build:
      context: ./
      dockerfile: ../../docker/nest/Dockerfile
    restart: unless-stopped
    ports:
      - 3333:8100
