version: "3.8"
services:
  game-service:
    image: microservice-platform-game-service:1.0.0-dev
    container_name: microservice-platform-game-service-dev
    build:
      context: ../../
      dockerfile: docker/nest/dev.dockerfile
    working_dir: /home/node/workspace
    command: npx nx serve game-service
    restart: unless-stopped
    tty: true
    volumes:
      - ../../:/home/node/workspace
      - /home/node/workspace/apps/
      - .:/home/node/workspace/apps/game-service
      - /home/node/workspace/node_modules
    networks:
      - be-microservice-boilerplate_microservice-platform-network
    env_file:
      - ../../.env.global.dev
      - .env.dev

networks:
  be-microservice-boilerplate_microservice-platform-network:
    external: true
