version: "3.8"
services:
  notification-service:
    image: microservice-platform-notification-service:1.0.0
    container_name: microservice-platform-notification-service
    build:
      context: ./
      dockerfile: ../../docker/nest/Dockerfile
    restart: unless-stopped
    ports:
      - 3333:8000
