version: "3.8"
services:
  game-gateway:
    image: microservice-platform-game-gateway:1.0.0-dev
    container_name: microservice-platform-game-gateway-dev
    build:
      context: ../../
      dockerfile: docker/nest/dev.dockerfile
    working_dir: /home/node/workspace
    command: npx nx serve game-gateway
    restart: unless-stopped
    tty: true
    volumes:
      - ../../:/home/node/workspace
      - /home/node/workspace/apps/
      - .:/home/node/workspace/apps/game-gateway
      - /home/node/workspace/node_modules
    networks:
      - be-microservice-boilerplate_microservice-platform-network
    ports:
      - 3402:8400
    env_file:
      - ../../.env.global.dev
      - .env.dev

networks:
  be-microservice-boilerplate_microservice-platform-network:
    external: true
